version: "3.9"
services:
  db:
    image: "postgres:latest"
    container_name: postges13
    ports: 
        - "5432:5432"
    environment: 
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 111111
        POSTGRES_DB: postgres
        PGDATA: /var/lib/postgresql/data/postgres
    restart: always
  server:
    build: .
    container_name: serverflask
    ports: 
        - "5000:5000"
    restart: always
    links: 
        - "db"
        


    